// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package catalogcolumn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Name-0]
	_ = x[Vendor-1]
	_ = x[Architecture-2]
	_ = x[Repository-3]
	_ = x[BoardsManagerURL-4]
	_ = x[RepositoryDataFolder-5]
	_ = x[BranchName-6]
	_ = x[PackageIndexRepository-7]
	_ = x[PackageIndexFolder-8]
	_ = x[PackageIndexBranch-9]
	_ = x[Reference-10]
	_ = x[Notes-11]
	_ = x[Suppress-12]
	_ = x[EnumEnd-13]
}

const _Type_name = "NameVendorArchitectureRepositoryBoards Manager URLRepository Data FolderBranch NamePackage Index RepositoryPackage Index FolderPackage Index BranchReferenceNotesSuppressEnumEnd"

var _Type_index = [...]uint8{0, 4, 10, 22, 32, 50, 72, 83, 107, 127, 147, 156, 161, 169, 176}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
